### ISSUE TITLE
The WAR failed to start in Tomcat

### ISSUE THREAD

**Issue by jiangchuan1220** [cloudfoundry-incubator/brooklyn-service-broker#16]
I build the WAR from source code. When I try to deploy the WAR through brooklyn, it started but I can not connect to the broker. I checked the tomcat startup log, there is errors. Then I tried to deploy the WAR in a local tomcat directly, there is also errors. The log is as follows. My environment is jdk1.8 and tomcat 8.

```
12-Nov-2015 11:27:34.092 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized (OpenSSL 1.0.1m 19 Mar 2015)
12-Nov-2015 11:27:34.378 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-apr-8080"]
12-Nov-2015 11:27:34.407 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-apr-8009"]
12-Nov-2015 11:27:34.412 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 2481 ms
12-Nov-2015 11:27:34.467 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service Catalina
12-Nov-2015 11:27:34.468 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.0.26
12-Nov-2015 11:27:34.540 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive D:\workspace\apache-tomcat-8.0.26\webapps\brooklyn-service-broker.war
12-Nov-2015 11:27:50.037 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
12-Nov-2015 11:27:50.085 SEVERE [localhost-startStop-1] org.apache.catalina.core.ContainerBase.addChildInternal ContainerBase.addChild: start: 
 org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/brooklyn-service-broker]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:945)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1768)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.eclipse.jetty.websocket.jsr356.server.deploy.WebSocketServerContainerInitializer.isEnabled(WebSocketServerContainerInitializer.java:122)
	at org.eclipse.jetty.websocket.jsr356.server.deploy.WebSocketServerContainerInitializer.onStartup(WebSocketServerContainerInitializer.java:137)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5156)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 10 more

12-Nov-2015 11:27:50.088 SEVERE [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Error deploying web application archive D:\workspace\apache-tomcat-8.0.26\webapps\brooklyn-service-broker.war
 java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/brooklyn-service-broker]]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:729)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:945)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1768)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

12-Nov-2015 11:27:50.094 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive D:\workspace\apache-tomcat-8.0.26\webapps\brooklyn-service-broker.war has finished in 15,553 ms
12-Nov-2015 11:27:50.101 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory D:\workspace\apache-tomcat-8.0.26\webapps\docs
```

Is there any suggestion about this error?

Thanks.

**Comment by jiangchuan1220** [comment]
I succeed to deploy the WAR through cloudfoundry using cf push command and register the broker to cloudfoundry. But there is still error when deploying from brooklyn using blueprint. Tomcat start with error above.

**Comment by robertgmoss** [comment]
That log isn't very helpful, I'm afraid, it could be for any number of reasons.  The recommended approach is to deploy to CF, but I'm just taking a look at deploying it with Brooklyn now.  First thing I can see is that Brooklyn is installing Java 1.6, so that won't work, I'll dig deeper and see if I can get it working then share what I did.

**Comment by robertgmoss** [comment]
incidentally, it comes with a built in jetty application server so you can run:

    java -jar brooklyn-service-broker.war

putting your properties in `application.properties`

**Comment by robertgmoss** [comment]
I found the issue:  Since it comes with an embedded server you need to specify in `build.gradle` that it is a provided dependency.

    providedRuntime("org.springframework.boot:spring-boot-starter-jetty:1.2.5.RELEASE")

rather than

    compile("org.springframework.boot:spring-boot-starter-jetty:1.2.5.RELEASE")

`providedRuntime` is supposed to allow it to work in both settings, but it seems in this case it doesn't, which is why it has been left as `compile`.
